### Post one investor
POST {{investors}}/investors/test
Content-Type: application/json

{
  "password": "azerty1.",
  "investorData": {
    "username": "test",
    "firstname": "toast",
    "lastname": "toast",
    "email": "toast@student.vinci.be",
    "birthdate": "2023-01-01"
  }
}

### Get one investor
GET {{investors}}/investors/test

### Update one investor
PUT {{investors}}/investors/test
Content-Type: application/json

{
  "username": "test",
  "firstname": "toasté",
  "lastname": "toast",
  "email": "toast@student.vinci.be",
  "birthdate": "2023-01-01"
}

### Delete one investor
DELETE {{investors}}/investors/test
