### Post one execution
POST {{executions}}/execute/AAPL/picsous/cresus
Content-Type: application/json

{
  "ticker": "AAPL",
  "seller": "picsous",
  "buyer": "cresus",
  "buyOrderGuid": "172c014f-67a8-40d9-b2cd-371957dc5d7f",
  "sellOrderGuid": "bbb7cf11-1ee9-43bc-9b5c-881690af74cc",
  "quantity": 10,
  "price": 100.0
}
